INSERT IGNORE INTO permissions (code, description) VALUES
('view_dashboard', 'Ver dashboard'),
('view_reports', 'Ver reportes y vistas agregadas'),
('view_audit', 'Ver auditoria'),
('kpi_read', 'Ver KPIs'),
('kpi_create', 'Crear KPIs'),
('kpi_update', 'Editar KPIs'),
('kpi_delete', 'Eliminar KPIs'),
('assignment_read', 'Ver asignaciones'),
('assignment_create', 'Crear asignaciones'),
('assignment_update', 'Editar asignaciones'),
('assignment_close', 'Cerrar asignaciones'),
('curation_read', 'Ver curaduria'),
('curation_submit', 'Proponer curaduria'),
('curation_review', 'Aprobar/Rechazar curaduria'),
('curation_edit', 'Editar criterio en borrador'),
('measurement_read', 'Ver mediciones'),
('measurement_create_manual', 'Cargar mediciones manuales'),
('measurement_import', 'Importar mediciones'),
('measurement_run_ingest', 'Ejecutar ingestas'),
('measurement_approve', 'Aprobar mediciones');
